// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwPvbxp9a-ezZjEoUwdPPtz7BQfeSEkF4',
    appId: '1:919398316951:web:b320e4c4a154dc0a1962d2',
    messagingSenderId: '919398316951',
    projectId: 'motazen-f2cc8',
    authDomain: 'motazen-f2cc8.firebaseapp.com',
    databaseURL: 'https://motazen-f2cc8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'motazen-f2cc8.appspot.com',
    measurementId: 'G-1T4B2B6X6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgjbr63P_ObC7uEt_-2tMmlMTR_TIPnMw',
    appId: '1:919398316951:android:64c095d9b9bfb8a91962d2',
    messagingSenderId: '919398316951',
    projectId: 'motazen-f2cc8',
    databaseURL: 'https://motazen-f2cc8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'motazen-f2cc8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcVzPFn39F-qaYStG-UqDW3EUO_X5huNQ',
    appId: '1:919398316951:ios:87c2a3f8cc96ba8d1962d2',
    messagingSenderId: '919398316951',
    projectId: 'motazen-f2cc8',
    databaseURL: 'https://motazen-f2cc8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'motazen-f2cc8.appspot.com',
    iosClientId: '919398316951-1h0dtrdulfgqullo9qqh36pd7mm0u5pd.apps.googleusercontent.com',
    iosBundleId: 'com.example.motazen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcVzPFn39F-qaYStG-UqDW3EUO_X5huNQ',
    appId: '1:919398316951:ios:87c2a3f8cc96ba8d1962d2',
    messagingSenderId: '919398316951',
    projectId: 'motazen-f2cc8',
    databaseURL: 'https://motazen-f2cc8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'motazen-f2cc8.appspot.com',
    iosClientId: '919398316951-1h0dtrdulfgqullo9qqh36pd7mm0u5pd.apps.googleusercontent.com',
    iosBundleId: 'com.example.motazen',
  );
}
