name: motazen
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1
isar_version: ^3.0.2
environment:
  sdk: ">=2.18.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  cached_network_image: ^3.2.2
  image_picker: ^0.8.6
  im_stepper: ^1.0.1+1
  isar: ^3.0.2
  path_provider: ^2.0.11
  introduction_screen: ^3.0.2
  isar_flutter_libs: ^3.0.2
  fl_chart: ^0.62.0
  flutter_staggered_grid_view: ^0.6.2
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  firebase_auth: ^4.2.5
  google_fonts: ^4.0.3
  searchfield: ^0.7.2
  textfield_search: ^0.10.0
  flutter_multi_select_items: ^0.4.2
  flutter_custom_clippers: ^2.0.0
  provider: ^6.0.4
  bubble_tab_indicator: ^0.1.6
  date_field: ^3.0.1
  auto_size_text: ^3.0.0
  flutter_rating_bar: ^4.0.1
  rflutter_alert: ^2.0.4
  intl: ^0.17.0
  multiselect: ^0.1.0
  number_inc_dec: ^0.8.0
  flutter_spinbox: ^0.13.0
  get: ^4.6.5
  fluttertoast: ^8.1.1
  email_auth: ^1.0.0
  is_first_run: ^1.0.0
  mailer: ^6.0.0
  firebase_database: ^10.0.9
  percent_indicator: ^4.2.2
  syncfusion_flutter_charts: ^21.1.39
  firebase_storage: ^11.0.10
  photo_view: ^0.14.0
  scrollable_positioned_list: ^0.3.5
  directed_graph: ^0.3.7
  sorted: ^2.1.0
  flutter_slidable: ^3.0.0
  flutter_native_splash: ^2.2.17
  async: ^2.10.0
  sprung: ^3.0.1
  syncfusion_flutter_datepicker: ^21.1.39
  shimmer: ^2.0.0
  cron: ^0.5.1
  showcaseview: ^2.0.3
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.2
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0

flutter_native_splash:
 image: assets/images/Motazen_splash.png
 color: "#000000"
 android: true
 android_gravity: fill
 ios: true
 fill: true  

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/badges/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Frutiger
      fonts:
        - asset: assets/fonts/Frutiger-LT-Arabic-45-Light.ttf
          weight: 300

