name: motazen
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.24.0
  cloud_firestore: ^3.5.1
  im_stepper: ^1.0.1+1
  isar: ^3.0.0-dev.8
  path_provider: ^2.0.11
  introduction_screen: ^3.0.2
  isar_flutter_libs: ^3.0.2
  fl_chart: ^0.55.2
  flutter_staggered_grid_view: ^0.3.2
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  firebase_auth: ^3.5.0
  google_fonts: ^3.0.1
  flutter_multi_select_items: ^0.4.2
  flutter_custom_clippers: ^2.0.0
  provider: ^6.0.4
  bubble_tab_indicator: ^0.1.6
  date_field: ^3.0.1
  flutter_rating_bar: ^4.0.1
  rflutter_alert: ^2.0.4
  intl: ^0.17.0
  multiselect: ^0.0.7
  number_inc_dec: ^0.8.0
  flutter_spinbox: ^0.10.0
  get: ^4.6.5
  keyboard_visibility: ^0.5.6
  getwidget: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.0-dev.8
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700